-- CREANDO TABLA CON CAMPO POR DEFECTO
CREATE TABLE Empleados( 
    idEmpleado INT NOT NULL, 
    nombre VARCHAR(20) NOT NULL,
    edad INT NOT NULL,
    ciudad VARCHAR(50) DEFAULT 'No tiene'
);

-- INSERTAR DATOS EN CAMPOS POR DEFECTO.
INSERT INTO Empleados VALUES(1, 'Carlos', 30, DEFAULT); -- El campo por DEFAULT debe ser llenado con DEFAULT.

-- AÑADIENDO CAMPO POR DEFECTO A CAMPOS QUE NO LO TENIAN.
ALTER TABLE Empleados ADD CONSTRAINT DF_ciudad DEFAULT 'No tiene' FOR ciudad;

-- ELIMINAR CAMPO POR DEFECTO.
ALTER TABLE Empleados DROP CONSTRAINT DF_ciudad;
