-- BORRAR TABLA
DROP TABLE Empleados; -- DROP TABLE Nombre_Tabla;

-- ELIMINAR CAMPO DE TABLA
ALTER TABLE Empleados DROP COLUMN sexo;

-- ELIMINAR REGISTROS ESPECIFICOS DE UNA TABLA (elimina un registro que cumple con la condición)
DELETE FROM Empleados WHERE edad = 29;
DELETE FROM Empleados WHERE idEmpleado = 2;

-- ELIMINAR TODOS LOS REGISTROS DE UNA TABLA
TRUNCATE TABLE Empleados;
DELETE FROM Empleados;