-- COMENTARIO DE UNA LÍNEA

/*
COMENTARIO DE VARIAS LÍNEAS.
COMENTARIO DE VARIAS LÍNEAS.
COMENTARIO DE VARIAS LÍNEAS.
COMENTARIO DE VARIAS LÍNEAS.
COMENTARIO DE VARIAS LÍNEAS.
*/


-- HABILITAR LINEAS DE CÓDIGO (PARA VER LOS ERRORES)
-- TOOLS/OPTIONS/TEXT EDITOR/ALL LANGUAGES/GENERAL/LINE NUMBERS(Activar)