-- CREACIÓN DE TABLA SIMPLE
CREATE TABLE tabla1 (
    id_tabla1 INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(25) UNIQUE,  
    apellido VARCHAR(30) NOT NULL,
    fecha DATE NOT NULL,
    genero ENUM('M', 'F'),  
    pais VARCHAR(20) NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP
);
-- CREACIÓN DE TABLA CON CONDICIONAL
CREATE TABLE IF NOT EXISTS tabla1(
    id_tabla1 INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    nombre VARCHAR(25) UNIQUE,  
    apellido VARCHAR(30) NOT NULL,
    fecha DATE NOT NULL,
    genero ENUM('M', 'F'),  
    pais VARCHAR(20) NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP
);


