-- SELECCIONAR REGISTROS DE UNA TABLA
SELECT * FROM tabla1;
-- SELECCIONANDO FUNCIÓN "NOW" PARA VER LA FECHA ACTUAL
SELECT NOW();
-- SELECCIONANDO "CURRENT_TIMESTAMP" PARA VER LA FECHA ACTUAL
SELECT CURRENT_TIMESTAMP;
-- SELECCIONANDO UN CAMPOS DETERMINADOS EN UNA TABLA
SELECT pais FROM tabla1;